### ISSUE TITLE
First steps after installing?

### ISSUE THREAD

**Issue by masiorama** [daxslab/yii2-website-module#1]
Hello there, thank you for your plugin.
I installed on my Yii project (advanced template), but I do not understand how to use the module.

I applied the migrations,  and configured as noted in the readme, but once done there was an issue because the token was not available. I checked the table and indeed there was no record on the `website` table. I created a record on the fly, so I by-passed the error.

After that, no errors, but if I try to access and endpoint related to the module, I always receive 404.

Any suggestions?
Thanks in advance.

**Comment by masiorama** [comment]
Ok, I maybe got it.
I reverted my dummy website record from the table.

I executed via shell `yii website/create http://myurl.loc`, a token was generated, then I applied it to the configuration (as stated in the readme)... I guess this info could be added to the readme file, because it is indeed mandatory to have the module working as expected.
Thanks!

**Comment by masiorama** [comment]
Another question: I have frontend pointing to the domain `myurl.loc`, while the backend app is accessibile at `admin.myurl.loc`... I can now access frontend, but I didn't figure out so far how to manage the backend.

**Comment by glpzzz** [comment]
Hello and sorry for the poor docs. The idea is to configure the module both in frontend and  backend apps. In each case you must configure the `controllersNamespace` property of the module to `<module>/controllers/frontend` or `<module>/controllers/backend` depending on the case

Also you can try daxslab/yii2-advanced-website which is an advanced template with this module and others pre configured

**Comment by masiorama** [comment]
Hi @glpzzz , thanks for the prompt reply.

I'm already on daxslab/yii2-advanced-website, since I investigated and found that repo too. Still it doesn't work for me.
I followed this:
```
composer install

./init

//setup database in common/config/main-local.php

./yii migrate

./yii website/create https://yii2-advanced-website.loc

//set the resulting token in website module configuration in common/config/main-local.php
```
This way the config should be already there, ... except for 

On `init` I got this error , at the  very end of the `Error. Cannot create symlink /shared/httpd/yii2-advanced-website/frontend/web/uploads /shared/httpd/yii2-advance` but the script ends.

The rest seems to be ok.

Once I hit `https://yii2-advanced-website.loc` from my browser I get this: https://ibb.co/YLBfF8W

If I try to access the backend I get nothing at all.

I'm gonna try from scratch again in the next few minutes.

**Comment by glpzzz** [comment]
Thanks for all the feedback. Right now I'm AFK and answering from phone. In couple of hours I can go deep on this. 

This repo is the base for most of our yii2 apps but docs it's not really the best because it was a very internal tool. I'm sure I'm omitting some (important) details in the readme. 

I let you know as soon as possible.

**Comment by masiorama** [comment]
One thing I found out: the controllers configuration in the docs is wrong.
It is `website\daxslab\controllers\frontend` while it should be `daxslab\website\controllers\frontend`. The same for the backend.
